### ISSUE TITLE
Uncaught Error: Call to undefined method cli\Table::setAsciiPreColorized() in vendor/wp-cli/wp-cli/php/WP_CLI/Formatter.php:285

### ISSUE THREAD

**Issue by miya0001** [wp-cli/doctor-command#113]
It has an error on Travis CI.

```
Fatal error: Uncaught Error: Call to undefined method cli\Table::setAsciiPreColorized() in vendor/wp-cli/wp-cli/php/WP_CLI/Formatter.php:285
Stack trace:
#0 vendor/wp-cli/wp-cli/php/WP_CLI/Formatter.php(138): WP_CLI\Formatter::show_table(Array, Array, false)
#1 vendor/wp-cli/wp-cli/php/WP_CLI/Formatter.php(89): WP_CLI\Formatter->format(Array, false)
#2 vendor/wp-cli/wp-cli/php/utils.php(288): WP_CLI\Formatter->display_items(Array)
#3 inc/class-command.php(261): WP_CLI\Utils\format_items('table', Array, Array)
#4 [internal function]: runcommand\Doctor\Command->list_(Array, Array)
#5 vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(81): call_user_func(Array, Array, Array)
#6 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array) in vendor/wp-cli/wp-cli/php/WP_CLI/Formatter.php on line 285
```

See https://travis-ci.org/wp-cli/doctor-command/jobs/261470000.

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/doctor-command/pull/112

**Comment by gitlost** [comment]
The `composer.lock` file is pointing to `php-cli-tools` 0.11.2 so if that's updated (or removed altogether) then the build should work...

**Comment by miya0001** [comment]
Via #114

**Comment by schlessera** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/4332
