### ISSUE TITLE
[PHP 8] Core check update test uses WordPress 4.4 which uses magic quotes

### ISSUE THREAD

**Issue by TimothyBJacobs** [wp-cli/doctor-command#155]
Similar to wp-cli/core-command#172.

```
$ wp theme activate twentyfifteen

    PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-check-core-update.feature.19-5fac5886b01f93.25946184/wp-includes/load.php:610
    Stack trace:
    #0 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-settings-cli.php(339): wp_magic_quotes()
    #1 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1253): require('/Users/timothyb...')
    #2 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1172): WP_CLI\Runner->load_wordpress()
    #3 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #4 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #5 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
    #6 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/boot-fs.php(17): require_once('/Users/timothyb...')
    #7 {main}
      thrown in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-check-core-update.feature.19-5fac5886b01f93.25946184/wp-includes/load.php on line 610
    Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-check-core-update.feature.19-5fac5886b01f93.25946184/wp-includes/load.php:610
    Stack trace:
    #0 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-settings-cli.php(339): wp_magic_quotes()
    #1 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1253): require('/Users/timothyb...')
    #2 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1172): WP_CLI\Runner->load_wordpress()
    #3 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #4 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #5 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
    #6 /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli/php/boot-fs.php(17): require_once('/Users/timothyb...')
    #7 {main}
      thrown in /private/var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-check-core-update.feature.19-5fac5886b01f93.25946184/wp-includes/load.php on line 610
    cwd: /var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-check-core-update.feature.19-5fac5886b01f93.25946184/
    run time: 0.25858902931213
    exit status: 255
    In step `And I run `wp theme activate twentyfifteen`'.                      # /Users/timothybjacobs/Workspace/wp-cli-dev/wp-cli-tests/features/steps/when.php:29
    From scenario `WordPress has a new minor version but no new major version'. # features/check-core-update.feature:19
    Of feature `Check whether WordPress is up to date'.
```

**Comment by danielbachhuber** [comment]
Probably no longer an issue https://github.com/wp-cli/core-command/issues/172#issuecomment-1435315801
